version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/serverless-sns-to-sqs-events
    steps:
      - checkout
      - run: npm ci

  deploy:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/serverless-sns-to-sqs-events
    steps:
      - checkout
      - run: npm ci
      - run: npm run semantic-release -- --allow-same-version

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: master

  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

